### ISSUE TITLE
Internet connection checking

### ISSUE THREAD

**Issue by saitej-janjirala** [HemanshuVarma/Internet-Connectivity#1]
you have added only for wifi and in that onlosing is never called

**Comment by HemanshuVarma** [comment]
Hello Saiteja,

Yes, that's expected. At least for now, as application does not handle connectivity via multiple modes like Wi-Fi and Cellular. _onLosing_ will be triggered when making a switch between network. But i'm are only handling Wi-Fi network now.

From the [documentation](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#onLosing(android.net.Network,%20int)),

`Called when the network is about to be lost, typically because there are no outstanding requests left for it. This may be paired with a NetworkCallback#onAvailable call with the new replacement network for graceful handover. This method is not guaranteed to be called before NetworkCallback#onLost is called, for example in case a network is suddenly disconnected.`

Will work on it soon or you can improve this and raising a PR. 😄

**Comment by saitej-janjirala** [comment]
done
